language: objective-c
osx_image: xcode9.1	
notifications:
  email: false
git:
  submodules: false
script: wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify
